### PR TITLE
Fix endless loop while createTaskIterator gets a function that return…

### LINKED ISSUE #1750: Browser freezes in 1.0.0
### Steps to reproduce
Needs to be investigated.

#### Description of the bug/issue
After upgrading from 0.16.2 to 1.0.0 and running the app, the browser (Chrome) gets stuck in what seems like a `while` loop and ceases to respond. Other than changes to the imports of `delay` from `redux-saga` to `redux-saga/effects` and `task.done` to `task.toPromise()`, no code changes were done. Reverting back to 0.16.2 resolves the issue.

#### Steps to reproduce the bug/issue
Needs to be investigated.

#### Example
Needs to be created.

### Actual results
The browser becomes unresponsive.

### The Expected results
A responsive browser.

### Environment information
1.0.0

### PR DESCRIPTION
**Pull request by shinima**
…s a Promise resolved with undefined.

| Q                        | A  |
| ------------------------ | ---  |
| Fixed Issues?            | Fixes #1750 |
| Patch: Bug Fix?          |  👍  |
| Major: Breaking Change?  |    |
| Minor: New Feature?      |    |
| Tests Added + Pass?      | Yes |
| Any Dependency Changes?  |    |

In the previous implementation, if the function passed to `createTaskIterator` returns a promise which resolves to be undefined, the iterator created by `createTaskIterator` will lead to an endless loop.

In the PR, I use `let resolved = false` to make sure that the promise is interpreted at most once.

### CODE REVIEW

File: packages/core/src/internal/effectRunnerMap.js [hunk 1]
```diff
@@ -37,10 +37,17 @@ function createTaskIterator({ context, fn, args }) {
       return result
     }
 
-    const next = (value = result) => ({
```
Comment (shinima) [inline packages/core/src/internal/effectRunnerMap.js]: If the promise resolves to be `undefined`, next time `next` is called with the resolved value, the default argument `result` is used.

**Comment by Andarist** [comment]
Thanks ❤️
